# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  Sigmedia - Signal Processing and Media Applications
author: Sigmedia
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Sigmedia Signal Processing and Media Applications, is a research group in
  Trinity College Dublin started in early 2000s by Anil Kokaram. Current focus
  of the research group is on signal processing applications for both video and
  audio related applications.
baseurl: ""
url: ""

google_analytics: ""

include:
  - _pages

sass_dir: ./_sass

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

# Where things are 
source              : .
destination         : ./_site

detach              : false
show_dir_listing    : false
permalink           : date
paginate_path       : /page:num
timezone            : null
port                : 4000
host                : 127.0.0.1

collections:
  members:
    output          : true
    sort_by         : date
  # TODO: Fix the Layout before enabling.
  #blog:
  #  output          : true
  #  sort_by         : date
  # permalink       : /:collection/:date/:name